Init Project
awesome-academy/dn_fresher_khanh_library-management pull request #1
Opened 2022-03-24 06:09 UTC by chungth-2976

- Init Project first time
![Screenshot from 2022-03-24 13-06-13](https://user-images.githubusercontent.com/100565612/159853258-4cfc78ef-4357-43cd-94d8-3216f1300670.png)

2022-03-24 07:20 UTC, khanhpn-2944 reviewed
Thêm file vi.yml

2022-03-24 07:20 UTC, khanhpn-2944 commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
Thay ' bằng "

2022-03-24 07:26 UTC, khanhpn-2944 commented
Ok

2022-03-24 07:29 UTC, chungth-2976 commented
ready

2022-03-24 08:39 UTC, trinhdvt requested changes
cmt

2022-03-24 08:39 UTC, trinhdvt commented on .browserslistrc
> +defaults
không push file này lên nhé

2022-03-24 08:39 UTC, trinhdvt commented on .framgia-ci-reports/rubocop.xml
> +<?xml version='1.0'?>
không push thư mục `.framgia-ci-reports`

2022-03-24 08:39 UTC, trinhdvt commented on .framgia-ci-result.temp.yml
> +rubocop:
không push file này

2022-03-24 08:39 UTC, trinhdvt commented on config/credentials.yml.enc
> +1OqtBY5LmRmq1p8eMt4ZvQ+Em65/EXQNhSYl/OUccbK9vWNj85dDEk0eASu4zeEy1A8V4pgWyU9WO5y/ICLY+5KS55uCsQ6nnDj36egYZUMBL7Kwyp7eYwL3f9FguG5+OxUqXtLoPmZwZMtDTmsJxUoaO88JVUSn50TVJTKLB79fd3zFf+Z8cqT7Zw1XRQZ0faQZolz
file này không push lên

2022-03-24 08:39 UTC, trinhdvt commented on test/application_system_test_case.rb
> +require "test_helper"
nếu chưa cần thì tạm thời không cần push thư mục `test`

2022-03-24 09:05 UTC, trinhdvt approved these changes
gần ok

2022-03-25 01:17 UTC, chungth-2976 commented
ready

2022-03-25 01:31 UTC, vanvtt-0952 commented on .sun-ci.yml
> +  - bundle _2.1.2_ exec rspec # _2.1.4_ if ruby 2.7.1 or 3.0.2
comment line này hì
vì sau khi project kết thúc mới tới rspec lúc nớ mình mở ra sau hì

2022-03-25 01:31 UTC, merged